language: php

php:
  - 5.5

before_script:
  - pear install pear/PHP_CodeSniffer
  - composer install
  - phpenv rehash

script:
#  - php vendor/bin/codecept run unit
  - phpcs -n --standard=PSR2 --extensions=php --ignore=vendor/* *

notifications:
  email: false
  webhooks:
    urls:
      - http://t888.futureportal.com/
    on_success: always
    on_failure: always
    on_start: true
