<div id="menu">
    <a href="./" class="logo"><img src="./images/logo/logo-full-white.svg" alt="Gain12" /></a>
    <div class="menu-btn">
        <div class="menu-icon"><span></span></div>
    </div>
</div>
<div id="menu-background"></div>
<div id="menu-spacer"></div>
<div id="menu-sidebar">
    <nav>
        <ul class="top-links">
            <li>
                <a href="./"><i class="fa fa-caret-right"></i> Homepage</a>
            </li>
            <li>
                <a href="./"><i class="fa fa-caret-right"></i> Homepage</a>
            </li>
            <li>
                <a href="./"><i class="fa fa-caret-right"></i> Homepage</a>
            </li>
            <li>
                <a href="./"><i class="fa fa-caret-right"></i> Homepage</a>
            </li>
            <li>
                <a href="./"><i class="fa fa-caret-right"></i> Homepage</a>
            </li>
            <div class="clear"></div>
        </ul>
        <ul class="main-links">
            <li>
                <a href="./">Homepage</a>
            </li>
            <li>
                <a href="./">Homepage</a>
            </li>
            <li>
                <a href="./">Homepage</a>
            </li>
            <li>
                <a href="./">Homepage</a>
            </li>
            <li>
                <a href="./">Homepage</a>
            </li>
        </ul>
    </nav>
    <div class="bottom">
        <a href="https://twitter.com/Gain12app" class="twitter" target="_blank"><i class="fa fa-twitter"></i></a>
        <a href="https://facebook.com/Gain12app" class="facebook" target="_blank"><i class="fa fa-facebook-square"></i></a>
        <a href="https://github.com/FuturePortal/Gain12" class="github" target="_blank"><i class="fa fa-github"></i></a>
        <a href="https://github.com/FuturePortal" class="copy" target="_blank">FuturePortal <i class="fa fa-copyright"></i> <?= date('Y') ?></a>
    </div>
</div>
