<!DOCTYPE html>
<html>
<head>
    <title><?= $title ?></title>
    <base href="<?= $siteUrl ?>" />
    <link rel="stylesheet" type="text/css" href="./css/main.css" />
    <link rel="stylesheet" type="text/css" href="./css/animate.css" />
    <script type="text/javascript" src="./js/jquery.js"></script>
    <script type="text/javascript" src="./js/menu.js"></script>
</head>
<body>
    <?= $content ?>
