<div id="header" class="hero-header">
    <div class="bg-video">
        <iframe width="1920" height="1080" src="//www.youtube.com/embed/x_W_hwGdr08?rel=0&wmode=opaque&autoplay=1" frameborder="0"></iframe>
    </div>
    <div class="overlay">
        <div class="gainer">
            <div class="top">Gain 12 characteristics</div>
            <div id="characteristic">Confidence</div>
            <div class="bottom">in 12 weeks</div>
        </div>
        <div class="scroller">
            <i class="fa fa-arrow-down"></i> Scroll down for more info <i class="fa fa-arrow-down"></i>
        </div>
    </div>
</div>
